### ISSUE TITLE
error on launching, please see the error below:

### ISSUE THREAD

**Issue by brakela** [MouseLand/rastermap#11]
Traceback (most recent call last):
  File "/home/idl/anaconda3/envs/rastermap/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/idl/anaconda3/envs/rastermap/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/idl/anaconda3/envs/rastermap/lib/python3.9/site-packages/rastermap/__main__.py", line 2, in <module>
    from rastermap import gui
  File "/home/idl/anaconda3/envs/rastermap/lib/python3.9/site-packages/rastermap/gui.py", line 12, in <module>
    import rastermap.run
  File "/home/idl/anaconda3/envs/rastermap/lib/python3.9/site-packages/rastermap/run.py", line 6, in <module>
    class RunWindow(QtGui.QDialog):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QDialog'

**Comment by penguingiraffe2** [comment]
Getting same error - any resolution?

**Comment by penguingiraffe2** [comment]
This looks like an issue between things written for pyqt4 but what is being installed is pyqt5

**Comment by jbscherrer** [comment]
I'm also getting this issue--did anyone figure out a workaround?

**Comment by nataliekoh** [comment]
Encountering this same issue on Windows 10!

**Comment by carsen-stringer** [comment]
please `pip install rastermap --upgrade`, this code has been removed

**Comment by nataliekoh** [comment]
Hi Carsen, I've done that (both just, and also about an hour ago), but I am still encountering the same error. The installation step says any version of Python > 3.0 should work; but do you have a recommended version, e.g. 3.9 instead of 3.7 maybe? I can try a fresh install in a new conda environment to see if that gets rid of the issue. Thanks!

**Comment by carsen-stringer** [comment]
Ah yes please try making a new environment, you need python 3.8 or higher
