### ISSUE TITLE
Data with a standard deviation of 0 prevents rastermap from running

### ISSUE THREAD

**Issue by Vanwalleghem** [MouseLand/rastermap#6]
When running rastermap with default settings and alpha of 1.43 on a dataset with 2 time series that have a standard deviation of 0, the resulting error occurs. 
```python
size of rastermap matrix
(892, 1200)
(1200,)
nmin 200
0.0049860477447509766
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\rastermap\__main__.py", line 47, in <module>
    model.fit(S[:, train_time])
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\rastermap\mapping.py", line 675, in fit
    model = PCA(n_components=nmin).fit(X0)
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\sklearn\decomposition\pca.py", line 341, in fit
    self._fit(X)
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\sklearn\decomposition\pca.py", line 382, in _fit
    copy=self.copy)
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\sklearn\utils\validation.py", line 542, in check_array
>>>ERROR<<<
    allow_nan=force_all_finite == 'allow-nan')
  File "C:\ProgramData\Anaconda3\envs\mouseland\lib\site-packages\sklearn\utils\validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
Interrupted by error (not finished)
```

Not sure it's that important as it's the responsibility of the user to use clean data

**Comment by carsen-stringer** [comment]
thanks for reporting this, we've fixed this now I hope!
