### ISSUE TITLE
install and run fail on Windows

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/rastermap#7]
Hi, 

I installed the github version of rastermap on Windows 10. I was able to create and activate the rastermap environment, but when I tried to run it I got the following error:

"

(rastermap) C:\Users\McCormick Lab\Documents\GitHub\rastermap>python -m rastermap
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\McCormick Lab\Documents\GitHub\rastermap\rastermap\__main__.py", line 2, in <module>
    from rastermap import gui
  File "C:\Users\McCormick Lab\Documents\GitHub\rastermap\rastermap\gui.py", line 7, in <module>
    import pyqtgraph as pg
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import *
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "C:\ProgramData\Anaconda3\envs\rastermap\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'
"

Can you help?

Thanks,

Evan

**Comment by vickerse1** [comment]
nevermind I figured it out.

thanks

evan
